In [1]:
# !pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
# !pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
# !pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
# !pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
# !pip install torch-geometric
# !pip install torch-geometric-temporal

In [2]:
import numpy as np
import sys
from torch_geometric_temporal.dataset import METRLADatasetLoader
from torch_geometric_temporal.signal import StaticGraphTemporalSignal

loader = METRLADatasetLoader()
dataset = loader.get_dataset(num_timesteps_in=12, num_timesteps_out=12)

print("Dataset type:  ", dataset)
print("Number of samples / sequences: ",  len(list(dataset)))

Dataset type:   <torch_geometric_temporal.signal.static_graph_temporal_signal.StaticGraphTemporalSignal object at 0x0000024794713FD0>
Number of samples / sequences:  34249


In [3]:
display(dataset.edge_index)


array([[  0,   0,   0, ..., 206, 206, 206],
       [  0,  13,  37, ..., 187, 198, 206]], dtype=int64)

In [4]:
display(dataset.edge_weight)

array([1.        , 0.22234692, 0.5088465 , ..., 0.27790868, 0.32041067,
       1.        ], dtype=float32)

In [5]:
display(((dataset.features)))

[array([[[ 0.53317183,  0.44864222,  0.51461655, ...,  0.48987615,
           0.57509303,  0.4280252 ],
         [-1.7291821 , -1.7171322 , -1.7050823 , ..., -1.6207328 ,
          -1.6086829 , -1.596633  ]],
 
        [[ 0.69398445,  0.74002916,  0.5022464 , ...,  0.3909146 ,
           0.49812302,  0.70016956],
         [-1.7291821 , -1.7171322 , -1.7050823 , ..., -1.6207328 ,
          -1.6086829 , -1.596633  ]],
 
        [[ 0.66924405,  0.5860887 ,  0.3166934 , ...,  0.44039539,
           0.5695954 ,  0.6568738 ],
         [-1.7291821 , -1.7171322 , -1.7050823 , ..., -1.6207328 ,
          -1.6086829 , -1.596633  ]],
 
        ...,
 
        [[ 0.2795828 ,  0.11327237,  0.38472947, ..., -0.14100395,
           0.3441828 ,  0.16825101],
         [-1.7291821 , -1.7171322 , -1.7050823 , ..., -1.6207328 ,
          -1.6086829 , -1.596633  ]],
 
        [[ 0.7620205 ,  0.7345311 ,  0.80443245, ...,  0.62594837,
           0.6740546 ,  0.63831854],
         [-1.7291821 , -1.7171322 , -

In [6]:
display(len((dataset.features)))

34249

In [7]:
display(dataset.snapshot_count)

34249

In [8]:
display(dataset.t)

0

In [9]:
display(dataset.targets)

[array([[ 0.37235928,  0.24522121,  0.49606127, ...,  0.3909146 ,
          0.47613147,  0.56409734],
        [ 0.66305894,  0.44864222,  0.66305894, ...,  0.415655  ,
          0.5201146 ,  0.46513578],
        [ 0.2424722 ,  0.60258245,  0.06928942, ...,  0.42184007,
          0.5311103 ,  0.7620205 ],
        ...,
        [-0.02348707, -0.05166355,  0.03217882, ...,  0.33524868,
          0.42665067,  0.415655  ],
        [ 0.8115013 ,  0.6245738 ,  0.67542917, ...,  0.8115013 ,
          0.6795527 ,  0.52080166],
        [ 0.48987615,  0.43214852,  0.2362871 , ...,  0.230102  ,
          0.46513578,  0.353804  ]], dtype=float32),
 array([[ 0.24522121,  0.49606127,  0.65206325, ...,  0.47613147,
          0.56409734, -0.00218275],
        [ 0.44864222,  0.66305894,  0.59158677, ...,  0.5201146 ,
          0.46513578,  0.60258245],
        [ 0.60258245,  0.06928942,  0.7180378 , ...,  0.5311103 ,
          0.7620205 ,  0.5311103 ],
        ...,
        [-0.05166355,  0.03217882,  0.3

In [10]:
display(len(dataset.targets[0]))

207

In [11]:
# Show first sample
next(iter(dataset))

Data(x=[207, 2, 12], edge_index=[2, 1722], edge_attr=[1722], y=[207, 12])

In [12]:
import seaborn as sns
# Visualize traffic over time
sensor_number = 1
hours = 24
sensor_labels = [bucket.y[sensor_number][0].item() for bucket in list(dataset)[:hours]]
sensor_labels

[0.6630589365959167,
 0.44864222407341003,
 0.6630589365959167,
 0.5915867686271667,
 0.588837742805481,
 0.6135781407356262,
 0.39366358518600464,
 0.5084314346313477,
 0.3785443902015686,
 0.4156549870967865,
 0.5201146006584167,
 0.465135782957077,
 0.6025824546813965,
 0.700169563293457,
 0.5750930309295654,
 0.5208016633987427,
 0.6080800890922546,
 0.5084314346313477,
 0.5764675736427307,
 0.44864222407341003,
 0.4871271550655365,
 0.5782346725463867,
 0.6685569882392883,
 0.5579122304916382]

In [13]:
# # Visualize traffic over time
# sns.lineplot(data=sensor_labels)

In [14]:
from torch_geometric_temporal.signal import temporal_signal_split
train_dataset, test_dataset = temporal_signal_split(dataset, train_ratio=0.8)

print("Number of train buckets: ", len(list(train_dataset)))
print("Number of test buckets: ", len(list(test_dataset)))

Number of train buckets:  27399
Number of test buckets:  6850


In [15]:
import torch
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import A3TGCN

class TemporalGNN(torch.nn.Module):
    def __init__(self, node_features, periods):
        super(TemporalGNN, self).__init__()
        # Attention Temporal Graph Convolutional Cell
        self.tgnn = A3TGCN(in_channels=node_features, 
                           out_channels=32, 
                           periods=periods)
        # Equals single-shot prediction
        self.linear = torch.nn.Linear(32, periods)

    def forward(self, x, edge_index):
        """
        x = Node features for T time steps
        edge_index = Graph edge indices
        """
        h = self.tgnn(x, edge_index)
        h = F.relu(h)
        h = self.linear(h)
        return h

TemporalGNN(node_features=2, periods=12)

TemporalGNN(
  (tgnn): A3TGCN(
    (_base_tgcn): TGCN(
      (conv_z): GCNConv(2, 32)
      (linear_z): Linear(in_features=64, out_features=32, bias=True)
      (conv_r): GCNConv(2, 32)
      (linear_r): Linear(in_features=64, out_features=32, bias=True)
      (conv_h): GCNConv(2, 32)
      (linear_h): Linear(in_features=64, out_features=32, bias=True)
    )
  )
  (linear): Linear(in_features=32, out_features=12, bias=True)
)

In [16]:
# GPU support
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
subset = 2000

# Create model and optimizers
model = TemporalGNN(node_features=2, periods=12).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
model.train()

print("Running training...")
for epoch in range(10): 
    loss = 0
    step = 0
    for snapshot in train_dataset:
        snapshot = snapshot.to(device)
        # Get model predictions
        y_hat = model(snapshot.x, snapshot.edge_index)
        # Mean squared error
        loss = loss + torch.mean((y_hat-snapshot.y)**2) 
        step += 1
        if step > subset:
          break

    loss = loss / (step + 1)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print("Epoch {} train MSE: {:.4f}".format(epoch, loss.item()))

Running training...
Epoch 0 train MSE: 0.7458
Epoch 1 train MSE: 0.7309
Epoch 2 train MSE: 0.7158
Epoch 3 train MSE: 0.6986
Epoch 4 train MSE: 0.6790
Epoch 5 train MSE: 0.6575
Epoch 6 train MSE: 0.6346
Epoch 7 train MSE: 0.6114
Epoch 8 train MSE: 0.5893
Epoch 9 train MSE: 0.5695


In [27]:
(y_hat)

tensor([[0.2968, 0.1453, 0.2889,  ..., 0.1477, 0.0872, 0.1949],
        [0.5153, 0.4104, 0.5499,  ..., 0.3649, 0.3506, 0.3911],
        [0.4835, 0.4057, 0.5084,  ..., 0.3606, 0.3442, 0.3685],
        ...,
        [0.2377, 0.0886, 0.2186,  ..., 0.1088, 0.0385, 0.1440],
        [0.4349, 0.3504, 0.4646,  ..., 0.3154, 0.3001, 0.3454],
        [0.4159, 0.3385, 0.4430,  ..., 0.3061, 0.2903, 0.3337]],
       grad_fn=<AddmmBackward0>)

In [17]:
model.eval()
loss = 0
step = 0
horizon = 288

# Store for analysis
predictions = []
labels = []

for snapshot in test_dataset:
    snapshot = snapshot.to(device)
    # Get predictions
    y_hat = model(snapshot.x, snapshot.edge_index)
    # Mean squared error
    loss = loss + torch.mean((y_hat-snapshot.y)**2)
    # Store for analysis below
    labels.append(snapshot.y)
    predictions.append(y_hat)
    step += 1
    if step > horizon:
          break

loss = loss / (step+1)
loss = loss.item()
print("Test MSE: {:.4f}".format(loss))

Test MSE: 0.6734


In [18]:
import numpy as np

sensor = 123
timestep = 11 
preds = np.asarray([pred[sensor][timestep].detach().cpu().numpy() for pred in predictions])
labs  = np.asarray([label[sensor][timestep].cpu().numpy() for label in labels])
print("Data points:,", preds.shape)

Data points:, (289,)


In [19]:
# import matplotlib.pyplot as plt 
# plt.figure(figsize=(20,5))
# sns.lineplot(data=preds, label="pred")
# sns.lineplot(data=labs, label="true")